### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by jamezrin** [ComputerElite/BVS#1]
I'm not sure why is the automatic update mechanism you have going on here is necessary at all.

It's very easy for you to change the `Update.txt` file to some malware or something and have all of your users execute that.

In fact, I'm not sure why this program is needed at all, considering PEP already supports this feature, but oh well...

**Comment by ComputerElite** [comment]
Hi. automatic Updates are there that they always have the right Version. cause if someone found a big Bug I'll resolve it. And yes it is easy to change Update.txt to Malware. But that goes for every Program. But the Update Process needs to be a exe that is the name of the program. Only then it is executed. If you want I'll change it to only accept files from this repository. otherwise it won't download the Update. I'm Open-Source for exactly those reasons. That people can check if I'm doing malicous stuff. And I do the Programs because I want a challenge and I'm bored. And when I got a working program I publish.
